### PR TITLE
Rename ili9431 and ili9441 to ili9341

### PR DESCRIPTION
**Pull request by frmdstryr**
Spent nearly an entire afternoon attempting to get this to work in parallel mode only to find out my board has an __ili9481__ driver and this project is for the __ili9341__ despite having __ili9431__ in the title.  

The title/repo should also be corrected.

### CODE REVIEW

**Comment by embeddedt** [comment]
(cc @amirgon, @kisvegabor)

**Comment by amirgon** [comment]
:+1: 
Looks like a typo, there is no such products "ili9431" or "ili9441", I think.

**Comment by kisvegabor** [comment]
Yes, it was typo. Sorry for that.

**Comment by frmdstryr** [comment]
Thank you!  Also, thanks for the great library, keep it up :+1:

**Pull request merged**
