### PR TITLE
Update README and code to support ESP_WROVER_KIT

### LINKED ISSUE #11: ili9341 driver backlight
Hello,

In `ili9341.c` i think there might be a mistake in the `ili9341_init()` function. I changed the last instruction to `gpio_set_level(ILI9341_BCKL, 0)` as opposed to `gpio_set_level(ILI9341_BCKL, 1)`. This might be due to the pull-up or pull-down config of the gpio but i am not sure.
Posted this for anybody that might encounter this.

### PR DESCRIPTION
**Pull request by C47D**
This PR fix #11 and updates:

- The README to add information about the ESP_WROVER_KIT (tomorrow i will take a picture of it running the demo) 0d4e8fd
- Some struct initialization on `disp_spi.c` and `tp_spi.c` 3f4196d
- Fixed a problem I'm having with the paths on the `component.mk` (it was pointing one directory below the actual directory target) 18ae5c1
- Add `ILI9341_BCKL_ACTIVE_LVL` on `drv\component.mk` to let the user set the correct enable level of back light b400229
- Add `TOUCH_SUPPORT` on `drv\component.mk` to let the user enable/disable touch input support 9422a1c

### CODE REVIEW

**Comment by C47D** [comment]
The code is tested and working :), one thing to notice is that the ESP Wrover Kit v4.1 have the programming UART on the ttyUSB1 port, i added a comment on the README about it.

**Comment by kisvegabor** [comment]
Looks good! I only miss a list of config options (like `TOUCH_SUPPORT`) from the README. What do you think?

**Comment by kisvegabor** [comment]
I got build errors:
```
In file included from /home/kisvegabor/projects/littlevgl/esp32_ili9341/components/lvgl/lvgl.h:19:0,
                 from /home/kisvegabor/projects/littlevgl/esp32_ili9341/components/drv/disp_spi.c:17:
/home/kisvegabor/projects/littlevgl/esp32_ili9341/components/lvgl/src/lv_misc/lv_log.h:17:21: fatal error: lv_conf.h: No such file or directory
```

I think it's because you changed the `../..` include path to `..`. `../..` seems logical to reach `lv_conf.h` from a component. I wonder how it compiles for you.

**Comment by C47D** [comment]
May be because I'm also moving both `lv_config.h` and `lv_ex_config.h` files into the component directory, maybe it's a better idea to move them over there.

**Comment by C47D** [comment]
Let me know what do you think @kisvegabor :)

**Comment by kisvegabor** [comment]
Aaand working! :slightly_smiling_face: 

I like the README too. Thank you very much!

**Comment by C47D** [comment]
Great, thanks for the patience @kisvegabor.

**Pull request merged**
